### ISSUE TITLE
Resolve issue with empty enums in the openapi yml config file

### ISSUE THREAD

**Issue by maximecarre1** [DFO-CHS-Dynamic-Hydrographic-Products/IWLS_pygeoapi#11]
Running pygeoapi openapi generate on the current build results in a yml config that doesn't pass validation checks due to the presence of an empty enum field in the description of the get methods for each collection.

**Comment by princessmittens** [comment]
Is this ready to be reviewed?

**Comment by maximecarre1** [comment]
Validation script for openapi yml file has been updated in pygeoapi version 0.14.0, but the same empty enum error remains.
