### ISSUE TITLE
Default behaviour of variable length strings

### ISSUE THREAD

**Issue by princessmittens** [DFO-CHS-Dynamic-Hydrographic-Products/IWLS_pygeoapi#17]
After more reading, default behavior of variable length strings in datasets for h5py are specifically encoded as byte strings. This is something we can look into further but I am not completely sure why byte strings are the default (compressibility maybe?). Given that is the default, perhaps we should consider keeping it as is and using the `dataset.asstr()` below to parse it. I have tested this and it works for the compound types as well. 

From the [h5py docs on strings](
https://docs.h5py.org/en/stable/strings.html): 

> String data in HDF5 datasets is read as bytes by default: bytes objects for variable-length strings, or numpy bytes arrays ('S' dtypes) for fixed-length strings. Use [Dataset.asstr()](https://docs.h5py.org/en/stable/high/dataset.html#h5py.Dataset.asstr) to retrieve str objects.

**Comment by maximecarre1** [comment]
Default string encoding while reading hdf files is dependent on  the version of the h5py library used. There are no changes required on our end.
