### ISSUE TITLE
Add coding review and guidelines for repo

### ISSUE THREAD

**Issue by princessmittens** [DFO-CHS-Dynamic-Hydrographic-Products/IWLS_pygeoapi#18]
Update README to contain coding procedures for the repo.

**Comment by maximecarre1** [comment]
It might be a good idea to check how others DFO repos README are structured on GitHub for inspiration:
[https://github.com/dfo-mpo](https://github.com/dfo-mpo)

**Comment by princessmittens** [comment]
This has been completed under MR #25.
