### ISSUE TITLE
S<104,111>-DCF8: S<104,111>_TypeOf<WaterLevel,Current>Data: Implement the observedMinusPredicted and observedMinusForecast data production.

### ISSUE THREAD

**Issue by glmcr** [DFO-CHS-Dynamic-Hydrographic-Products/IWLS_pygeoapi#37]

**Comment by glmcr** [comment]
related to #28

**Comment by maximecarre1** [comment]
Data reading and transformation for S-104/111 DCF8 hdf5 files was handled by issue #41 , I can had an option to compare the timeseries and generate basic statistics.
